import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cafe DelSol",
  description: "Generated by create next app",
  icons:{
   icon:['/favicon.ico?v=4'],
  apple:['/apple-touch-icon.png?v=4'],
    shortcut:['apple-touch-icon.png']
  }  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer ></Footer>
        </Providers>
      </body>
    </html>
  );
}
